# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-22 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateField(blank=True),
        ),
    ]
